spring:
  datasource:
    password: my-secret-pw
    username: root
    name: visits
    url: jdbc:mysql://some-mariadb:3306/visits
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
